name: Laravel Setup
description: Shared Laravel setup steps (PHP, Composer, .env)

inputs:
  php-version:
    description: "PHP version to install"
    required: false
    default: "8.2"

  extensions:
    description: "Comma-separated list of PHP extensions"
    required: false
    default: "mbstring, dom, curl, json"

  composer-token:
    description: "GitHub token for composer auth"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.extensions }}
        coverage: none

    - name: Copy .env
      run: cp .env.example .env
      shell: bash

    - name: Set Composer Auth (if token provided)
      if: ${{ inputs.composer-token != '' }}
      run: composer config --global github-oauth.github.com ${{ inputs.composer-token }}
      shell: bash

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist
      shell: bash

    - name: Generate application key
      run: php artisan key:generate
      shell: bash
